Flower\DriveBundle\Entity\Folder:
    type: entity
    table: drive_folder
    repositoryClass: Flower\DriveBundle\Repository\FolderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        level:
            type: integer
            nullable: true
        archived:
            type: boolean
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    oneToMany:
        folders:
          targetEntity: Flower\DriveBundle\Entity\Folder
          mappedBy: parent

        files:
          targetEntity: Flower\DriveBundle\Entity\File
          mappedBy: folder

    manyToOne:
        parent:
          targetEntity: Flower\DriveBundle\Entity\Folder
          inversedBy: folders
          joinColumn:
            name: parent_id
            referencedColumnName: id


    lifecycleCallbacks: {  }
